update push flow

diff --git a/.github/workflows/aquasec.yml b/.github/workflows/aquasec.yml
--- a/.github/workflows/aquasec.yml
+++ b/.github/workflows/aquasec.yml
@@ -38,20 +38,27 @@ jobs:
         uses: docker/build-push-action@v3
         with:
           push: true
-          tags: "saargondocker/graphql-vuln:${{ github.sha }}"
+          tags: "technicallysimpleme/graphql-vuln:${{ env.tag-version }}"
+          
       - name: Manifest Generation
         run: |
+          export BILLY_SERVER=https://billy.codesec.aquasec.com
           curl -sLo install.sh download.codesec.aquasec.com/billy/install.sh
           curl -sLo install.sh.checksum https://github.com/argonsecurity/releases/releases/latest/download/install.sh.checksum
-          if ! cat install.sh.checksum | shasum -a 256 ; then
-            echo "install.sh checksum failed"
-            exit 1
+          if ! cat install.sh.checksum | sha256sum ; then
+          echo "install.sh checksum failed"
+          exit 1
           fi
-          sh install.sh
+          BINDIR="." sh install.sh
           rm install.sh install.sh.checksum
-          billy generate \
-              --access-token "${{ secrets.GITHUB_TOKEN }}" \
-              --aqua-key "${{ secrets.AQUA_KEY }}" \
-              --aqua-secret "${{ secrets.AQUA_SECRET }}" \
-              --artifact-path "saargondocker/graphql-vuln:${{ github.sha }}" 
+          ./billy generate \
+            --access-token "${{ secrets.GITHUB_TOKEN }}" \
+            --aqua-key "${{ secrets.AQUA_KEY }}" \
+            --aqua-secret "${{ secrets.AQUA_SECRET }}" \
+            --artifact-path "technicallysimpleme/graphql-vuln:${{ env.tag-version }}" 
+
+            # The docker image name:tag of the newly built image
+            # --artifact-path "my-image-name:${{ env.tag-version }}" 
+            # OR the path to the root folder of your project. I.e my-repo/my-app 
+            # --artifact-path "${{env.MY_APP_ROOT}}"
 
